credentials:
  usernames:
    developer:
      email: developer@mail.com
      logged_in: False
      name: Developers
      password: abcd1234
    customer:
      email: customer@mail.com
      logged_in: False
      name: Customer 1
      password: abcd1234
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name